### ISSUE TITLE
report URI or email address for preload removal

### ISSUE THREAD

**Issue by graingert** [chromium/hstspreload.org#135]
recently procensus.com and procens.us was dropped from the preload set for seemingly no reason, and I would never have found out if I didn't happen to check manually.

Can we have a spec for an HSTS preload report-uri eg `mailto:admin+hsts@procensus.com`

**Comment by lgarron** [comment]
hstspreload.org purposely doesn't handle PII or send emails. If you want to avoid being removed without your knowledge, I suggest doing one of the following:

- Check against the canonical preload list in the Chromium source.
- Regularly check https://hstspreload.org/api/v2/status?domain=procens.us
- Contribute to https://bugs.chromium.org/p/chromium/issues/detail?id=621671 about how to associate contact emails with preload list entries.

**Comment by graingert** [comment]
@lgarron do you have API docs, eg https://hstspreload.org/api/v2/status?domain=procens.us&domain=procensus.com doesn't work as I'd expect.

**Comment by lgarron** [comment]
> @lgarron do you have API docs, eg https://hstspreload.org/api/v2/status?domain=procens.us&domain=procensus.com doesn't work as I'd expect.

Unfortunately, there are no API docs yet. However, `api/v2/status` and `api/v2/preloadable` always take exactly one `domain` parameter.
