### ISSUE TITLE
pending submission to the preload list

### ISSUE THREAD

**Issue by Nirjonadda** [chromium/hstspreload.org#139]
I submitted my domain to the HSTS Preload list about 1 months ago. I've been in compliance with their requirements for every moment since then. It still says I'm "pending submission to the preload list."
I'm wondering if anyone has any visibility behind this process and if I can have my expectations set for how long this might take?

**Comment by lgarron** [comment]
> I'm wondering if anyone has any visibility behind this process and if I can have my expectations set for how long this might take?

hstspreload.org states "Note that new entries are hardcoded into the Chrome source code and can take several months before they reach the stable version." and purposely doesn't commit to any timelines.

Routine updates are [simple to create, but still manual](https://github.com/chromium/hstspreload.org/wiki/Preload-List-Processes#updating-bulk-hsts-entries).
Usually, pending entries are added within 6 weeks, although that's up to @ericlaw1979.

https://bugs.chromium.org/p/chromium/issues/detail?id=736188 will automate this, hopefully to the point of being daily or weekly.
