### ISSUE TITLE
Removal based on domain expiry

### ISSUE THREAD

**Issue by strugee** [chromium/hstspreload.org#140]
Currently the removal form requires HTTPS but this doesn't work so hot when the domain is expired. The requirement should probably have an exception in that case.

**Comment by lgarron** [comment]
See:
- https://bugs.chromium.org/p/chromium/issues/detail?id=678807
- https://docs.google.com/document/d/1wiB3AbxqEb4tb1meepsv6sx36poFQozlDyPUJ2qCcbw/edit#bookmark=id.7wsbxeftm1o8
- https://docs.google.com/document/d/1F3JisdfbDkUj6a7jr7o27v3pqlvmwexuv8I4jJYaiuY/edit#bookmark=id.9llhhorfdrzk

*If* there is a secure, automated way to check for expired domains (at least for major TLDs), then we should be removing them automatically (#80). If there is a secure manual approach, the [contact email](https://hstspreload.org/#contact) should suffice.
