### ISSUE TITLE
Test domains

### ISSUE THREAD

**Issue by rwky** [chromium/hstspreload.org#147]
We're using hstspreload.org to run tests with travis builds of this script https://github.com/sensu-plugins/sensu-plugins-ssl/blob/master/test/check-ssl-hsts-preloadable_spec.rb

Up until recently garron.net issued warnings now it doesn't. It would be great if there were test domains that did the following:

1. passed preload check without any errors and warnings
2. passed preload checks with warnings
3. failed with errors

1 and 3 are easy to find, 2 is more difficult, would it be possible to get a domain that permanently generates warnings? If not can you suggest a better testing method?

**Comment by majormoses** [comment]
I think they remove them after a while if they have warnings such as the max age being too low. I actually had setup hsts and preloaded with them but when I checked it saw the warning and it had text about removal if not fixed so I fixed mine. I will have to look into what we can do about that. Maybe we can email the admin for https://hstspreload.org and ask them for suggestions or if it would be possible to flag an entry to keep it around with warnings. They may may have already solved this for their own testing and we can leverage that domain. Let me know if you want me to reach out or if you got it.

**Comment by majormoses** [comment]
Just double checked in your case it looks like you/your hosting provider fixed your warnings or they changed their requirements on what a warning is. We might be able to add another random domain but I'd like to see if there is already a standard testing domain?

**Comment by lgarron** [comment]
> I think they remove domains with warnings after a while?

Warnings don't impact whether a domain can become/stay preloaded.

https://github.com/chromium/hstspreload uses:
https://github.com/chromium/hstspreload/blob/master/redirects_test.go#L138

This issue belongs at https://github.com/chromium/hstspreload, so feel free to reopen there if there's more.
