### ISSUE TITLE
Redirect error: INTERNAL_ERROR

### ISSUE THREAD

**Issue by stmos** [chromium/hstspreload.org#161]
I have 3 sites with the same exact Nginx + SSL configuration. I was able to submit two of them, while on the third one I always get the same error:

```
Error: Error following redirects
Redirect error: Get https://www.mysite.com/: stream error: stream ID 1; INTERNAL_ERROR
```
Any ideas on what may be wrong? Thanks.

**Comment by lgarron** [comment]
Are you certain the configuration is the same on the `www` subdomain?

If so, any chance you're able to share which domain?

**Comment by nharper** [comment]
Also, are you able to reproduce using the command line tool in https://github.com/chromium/hstspreload?

Is there any chance you're doing something odd with HTTP/2 Trailers on that 3rd site?

**Comment by stmos** [comment]
Nevermind, it was a configuration issue. We previously blocked the user agent "Go-http-client" on that specific site (via Nginx) due to aggressive scraping. I'll close this, thanks!
