### ISSUE TITLE
Error: Cannot connect using TLS

### ISSUE THREAD

**Issue by florian2833z** [chromium/hstspreload.org#165]
Right now my server is already preloaded so everything is fine but I still wanted to report an error. If I enter "florian2833z.de", I get the following message:
```We cannot connect to https://florian2833z.de using TLS ("Get https://florian2833z.de: dial tcp [2a03:4000:29:1f1::1]:443: connect: network is unreachable").```

**Comment by lgarron** [comment]
I'm unable to connect to florian2833z.de where I am (in California).

**Comment by florian2833z** [comment]
> 
> 
> I'm unable to connect to florian2833z.de where I am (in California).

Can you give me your ip address so I can report that connection issues?

**Comment by lgarron** [comment]
> Can you give me your ip address so I can report that connection issues?

Would you mind emailing me for that? Thanks!
(My email is on my GH profile, or on my website.)

**Comment by florian2833z** [comment]
mail went out

**Comment by eallion** [comment]
My website has the same issue  
( [eallion.com](https://eallion.com) )

**Comment by Rohmilchkaese** [comment]
@eallion @nharper same issue with my domain:
We cannot connect to https://cevin.at using TLS ("Get https://cevin.at: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)").

Although I did manage to get it on the pending list. Is it now my mistake or the website's ?

**Comment by nharper** [comment]
The original issue reported on this thread indeed appears to be another case of #43 - please follow that issue for updates. The other domains mentioned in this thread are now on the preload list and are not showing any errors.
