### ISSUE TITLE
It should still be possible to restart the HSTS test

### ISSUE THREAD

**Issue by ZerooCool** [chromium/hstspreload.org#171]
If the site is validated, and added in preload, the following message is displayed:
Status: visionduweb.fr is currently preloaded.

If, in the meantime, changes in the configuration occur, the same message is displayed.

It should still be possible to restart the HSTS test, even for a site that has been validated and added in preload.

**Comment by nharper** [comment]
When entering a domain on hstspreload.org, two checks are done. One is to /api/v2/status, to check if the domain entered is on the preload list (or pending submission or removal), and the other is to /api/v2/preloadable, to check if the domain meets the preloading criteria. If the domain is already on the list and it meets all of the criteria, then "Status: [domain name] is currently preloaded." is displayed. If the domain is on the preload list (and was submitted via hstspreload.org) but has warnings or errors, those are also displayed. See https://github.com/chromium/hstspreload.org/blob/master/frontend/static/js/form.js#L109 for how that's handled.

**Comment by lgarron** [comment]
> If the domain is on the preload list (and was submitted via hstspreload.org) but has warnings or errors, those are also displayed. See

Nit: we suppress warnings.

**Comment by ZerooCool** [comment]
Ok I will check with use.

I am renewing my certificates and encrypting and making temporary changes, I would not want to break my hsts.

I will see if any warnings or error messages are displayed during my tests.

Thank you.
