### ISSUE TITLE
Fix HTML issues

### ISSUE THREAD

**Issue by DubbySlashy** [chromium/hstspreload.org#181]
The Nu Html Checker points out a single issue with the HTML of hstspreload.org. Please fix this issue.
https://validator.w3.org/nu/?doc=https%3A%2F%2Fhstspreload.org%2F

**Comment by nharper** [comment]
The error mentioned by the Nu Html Checker says that the `autocorrect` attribute isn't allowed on an `input` element. This attribute is an Apple extension (described at https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html) to disable autocorrect on the domain input.

According to the HTML spec (https://html.spec.whatwg.org/multipage/), this attribute is syntactically valid (https://html.spec.whatwg.org/multipage/syntax.html#attributes-2). I haven't found anything in https://html.spec.whatwg.org/multipage/ that disallows unspecified attributes on an input element. Given the utility of this attribute and that it doesn't hurt to include it, I see no reason to fix this.
