### ISSUE TITLE
Where is the list for hsts preload domain ?

### ISSUE THREAD

**Issue by ZerooCool** [chromium/hstspreload.org#193]
I have save this link with full list, but, now, this link is empty !???

Where i can found the full list domain hsts preload ?

https://source.chromium.org/chromium/chromium/src/+/master:net/http/transport_security_state_static.json

**Comment by nharper** [comment]
It appears there's a bug in the chromium code search site that is incorrectly displaying that the file is empty. The file lives in the chromium source repository which lives at chromium.googlesource.com and can also be found at https://chromium.googlesource.com/chromium/src/+/master/net/http/transport_security_state_static.json.

**Comment by ZerooCool** [comment]
@nharper Sorry, but, it's the same for me, i can't list the hsts domain preload.
