### ISSUE TITLE
Unexplained warning

### ISSUE THREAD

**Issue by teh-maxh** [chromium/hstspreload.org#200]
My site gets a warning for having an "unusually long" max-age. However, the warning message does not explain why this deserves to be a warning condition. (I've also tried searching this repo for information, but the warning message is not anywhere to be found.)

**Comment by nharper** [comment]
The warning comes from the hstspreload library at https://github.com/chromium/hstspreload/blob/be995c98f169479ab1938d94ecad0d95b42ea31a/header.go#L241.

This warning appears if the max-age is greater than 10 years. The reason for this warning is that browsers cap how large of a max-age it will store (for example, if Chrome sees a max-age greater than 365 days, it rounds the max-age down to 365 days).
