### ISSUE TITLE
Cannot add lancom.de

### ISSUE THREAD

**Issue by johnny** [chromium/hstspreload.org#211]
Hi,

I'm trying to add lancom.de to the preload list. Running the checks locally from my machine works:

```
hstspreload preloadabledomain lancom.de
Checking domain lancom.de for preload requirements...
Observed header: max-age=31536000; includeSubDomains; preload

Satisfies requirements.
```

But running it from the website gives timeout errors https://hstspreload.org/?domain=lancom.de. The site is accessible only through IPv4.

**Comment by nharper** [comment]
I get the same timeout error when I run the check from my workstation. My best guess is that the domain conditionally blocks TCP or TLS connections.
