### ISSUE TITLE
Change the main branch to `main`

### ISSUE THREAD

**Issue by lgarron** [chromium/hstspreload.org#217]
This project still uses `master` as its main branch. I think it would be good to switch to `main` (via project settings on GitHub).

**Comment by nharper** [comment]
I agree we should do this. Is this just a matter of renaming, according to the instructions at https://github.com/github/renaming#renaming-existing-branches?

For this and the hstspreload repo, I think the likelihood of breaking something by doing this rename is low, and the cost of fixing something broken should also be low.

**Comment by lgarron** [comment]
> I agree we should do this. Is this just a matter of renaming, according to the instructions at https://github.com/github/renaming#renaming-existing-branches?

Yep!

**Comment by nharper** [comment]
This is done.
