### ISSUE TITLE
`Strict-Transport-Security` header detected incorrectly

### ISSUE THREAD

**Issue by Big-Cake-jpg** [chromium/hstspreload.org#256]
Domain `lihaoyu.cn` has `Strict-Transport-Security: max-age=31536000;includeSubDomains;preload` header, but `hstspreload.org` said that this domain doesn't have any HSTS header.
![image](https://github.com/chromium/hstspreload.org/assets/76810494/ee373865-d72d-4bbc-bad9-3a22b0797b84)
![image](https://github.com/chromium/hstspreload.org/assets/76810494/ae1aa8e3-67a0-49b0-b0ee-f30fd2613d66)

Meanwhile, `www.lihaoyu.cn` is normal.
![image](https://github.com/chromium/hstspreload.org/assets/76810494/9af20e2f-771b-4b36-a80f-282adc1ef549)

**Comment by lgarron** [comment]
> but `hstspreload.org` said that this domain doesn't have any HSTS header.

Checking the response for `https://lihaoyu.cn` in Chrome DevTools and `cURL`/HTTPie, that looks correct. The site needs to resume sending the header to stay preloaded.

**Comment by nharper** [comment]
I concur with @lgarron's assessment. This appears to be a configuration issue with the website, not an issue with hstspreload.org. One possible explanation for why lgarron, hstspreload.org, and I don't see the HSTS header is that it's possible that the website only sends the HSTS header under some conditions.
