### ISSUE TITLE
IPv6-only

### ISSUE THREAD

**Issue by tobbe-eklov** [chromium/hstspreload.org#262]
Sites with only AAAA record isn't working
Ex
Error: Cannot connect using TLS
We cannot connect to https://dnssecandipv6.se using TLS ("Get \"https://dnssecandipv6.se\": dial tcp [2a07:1c80:102:193:100::10]:443: connect: cannot assign requested address")

That should be easy to fix I think.

//Tobbe

**Comment by nharper** [comment]
This is a duplicate of issue #43.

I wish it were an easy fix, but our infrastructure doesn't support IPv6, and that's not something we can fix for them ):

Still no updates on the internal tracking bug mentioned on #43.
