### ISSUE TITLE
Handle removal requests entirely through the site.

### ISSUE THREAD

**Issue by lgarron** [chromium/hstspreload.org#50]
People can't follow directions.

**Comment by InfinitudeUK** [comment]
Will you be preforming the verification manually or automated for removal from the preload list? If automated, will it preform email verification to one of the following email addresses:
admin@example.com, administrator@example.com, security@example.com and webmaster@example.com.

Are you going to allow this method for API use to selected domains like cloud.infinitude.me.uk?

**Comment by lgarron** [comment]
> Will you be performing the verification manually or automated for the removal of domains from the preload list? If you are going to automate the process, will it perform email verification to one of the following email addresses: admin@example.com, administrator@example.com, security@example.com and webmaster@example.com?

The current removal procedure is easy to automate without an email check: verify that the site is sending an HSTS header without `preload`.

As for the future, TBD. I don't want to reimplement entire parts of domain validation.
 
> Are you going to allow this method for API use to selected domains like cloud.infinitude.me.uk?

Probably not. The preload list is basically still experimental, and non-canonical layers of abstractions are problematic for us right now (a major reasons sites need to be removed is because they were following third-party advice). It's better to encourage stateful interactions with the preload list to go through hstspreload.appspot.com .

**Comment by lgarron** [comment]
This will probably be obsoleted by #50.

**Comment by lgarron** [comment]
We've automated as much as we can, for now.
