### ISSUE TITLE
Report requirements status even if a site is preloaded

### ISSUE THREAD

**Issue by CurtisLeeBolin** [chromium/hstspreload.org#55]
I had an error in my HSTS header but hstspreload.appspot.com didn't alert me to this error because my site was already in the preload list.

**Comment by lgarron** [comment]
For preloaded sites, we purposely don't show whether a site satisfies current requirements, because not all the same requirements apply to all sites on the list.

You can check for an individual site at the API endpoint:
https://hstspreload.appspot.com/api/v2/preloadable?domain=github.com

Once we have a database to keep track of which requirements apply to which site, we should show this data.

**Comment by CurtisLeeBolin** [comment]
Thanks.  I'm looking forward to it.

**Comment by lgarron** [comment]
> Once we have a database to keep track of which requirements apply to which site, we should show this data.

We can now query for bulk preloaded sites efficiently:
https://github.com/chromium/hstspreload.org/blob/b83053d5c4a6d082c3332a39d2e7e20279a8aa70/api/api.go#L22

**Comment by lgarron** [comment]
For https://twitter.com/vcsjones/status/910328524954902533

(I apologize ahead of the time that the JS code is not super-clean.)

We actually always race the `preloadable` and `status` checks: https://github.com/chromium/hstspreload.org/blob/78bc18e054d1631308caecde9ed50c8324d2e7f2/frontend/static/js/form.js#L38-L42

Right now, we always ignore the `preloadable` result if the `status` is `preloaded`. You have to tell it to show the issues here: https://github.com/chromium/hstspreload.org/blob/78bc18e054d1631308caecde9ed50c8324d2e7f2/frontend/static/js/form.js#L236

You'll also want to update the status string to explain "preloaded, but missing out on best practices (technically, requirements)".

Now, that will have the problem that you don't know if a domain is bulk preloaded, so the string will show even for domains where the requirements don't apply. I suggest attaching this to the `status` result by [extending](http://dennissuratna.com/using-anonymous-field-to-extend-in-go/) the [DomainState](https://godoc.org/github.com/chromium/hstspreload.org/database#DomainState) struct

https://github.com/chromium/hstspreload.org/blob/master/api/domain_handlers.go#L115

You should then be able to read the value in JS and decide to show the issues/custom status based on that.
