### ISSUE TITLE
Get Public Key Pinning Information from API

### ISSUE THREAD

**Issue by ByJamesBurton** [chromium/hstspreload.org#71]
Be quite beneficial to include public key pinning information in the api status response when I query:
https://hstspreload.appspot.com/api/v2/status?domain=0.me.uk
.

**Comment by lgarron** [comment]
This is probably reasonable to expose in the parsed preload list format in the underlying Go API.
However, the site is explicitly focused on HSTS, and HPKP is out of scope.

Since preloaded HPKP is a per-browser feature, and likely to stay that way, that's unlikely to change soon.

**Comment by lgarron** [comment]
That said, I always want to keep an open mind for new use cases.
What would be beneficial in this case?

**Comment by ByJamesBurton** [comment]
**First use case:**

Allows researchers, students and other interested parties who are interested in public key pinning to search specified domain names (e.g. Google.com ) using simple to use web interface to see if the domain has been embedded in the Google Chrome static public key pinning list. Also searching through the massive json preload list is not everyone's cup of tea and the information is sometimes dotted around the file. 

As well this information could be useful for the Mozilla Observatory project in deciding appropriate rating.

**Second use case:**

I'm in the process of creating simple monitoring application which sends me status emails very few months to check if the domains are successfully maintaining hsts preloaded status and I wanted to also check the status of public key pinning as well.
