### ISSUE TITLE
hstspreload.appspot.com doesn't send an HSTS header

### ISSUE THREAD

**Issue by lgarron** [chromium/hstspreload.org#73]
This breaks the [`www.no_tls whitelisted` case of the `TestPreloadableDomainAndRemovableDomain` test](https://github.com/chromium/hstspreload/blob/072783d483776e8749b20646f8362eec5a1d4b46/domain_test.go#L149) test for `hstspreload`.

**Comment by lgarron** [comment]
Note that we do try to set the header if `r.TLS != nil || maybeAppEngineHTTPS(r)`; perhaps sending the 301 redirect causes the header to be dropped, or maybe this is yet another silly edge case with Flexible Environment.

**Comment by ByJamesBurton** [comment]
According to Fiddler 4 and Google Chrome Dev Tools, hstspreload.appspot.com doesn't indeed send the HSTS header. 
![image](https://cloud.githubusercontent.com/assets/24654097/21964166/d0c701fa-db3e-11e6-9113-16b0404e14a7.png)
![image](https://cloud.githubusercontent.com/assets/24654097/21964169/e0dcc1c4-db3e-11e6-88a8-795d3a4f7f0e.png)

**Comment by lgarron** [comment]
> According to Fiddler 4 and Google Chrome Dev Tools, hstspreload.appspot.com does indeed send the HSTS header.

What about now?

I'm not seeing it in DevTools *or* `curl`.

**Comment by lgarron** [comment]
Woah, but [`bat`](https://github.com/astaxie/bat) gets a `200` with `Strict-Transport-Security : max-age=31536000; includeSubDomains; preload`

**Comment by ByJamesBurton** [comment]
Rechecked in Fiddler 4 and Google Chrome Dev Tools. Same Result. In DevTools you must tick the checkbox "disable cache".

![image](https://cloud.githubusercontent.com/assets/24654097/22103623/c6e0e44c-de33-11e6-95ca-0ddbe2a284a6.png)
![image](https://cloud.githubusercontent.com/assets/24654097/22103698/10f7386a-de34-11e6-98fd-ed859f0fca36.png)

**Comment by lgarron** [comment]
I just checked with my personal computer on a guest network, and it appears that the header is set for public responses, but stripped inside the Google corporate network.

<exasperation>ARARAGARHGARGHARHGHARGAHHHAHRGHRGAHRGAHGHARHHARHGAHRHGAHRHGAHRGHAHRGHARGHHAAHRGAHRG</exasperation>
