### ISSUE TITLE
hstspreload scanner does not see HSTS header from site using Lambda@Edge

### ISSUE THREAD

**Issue by graingert** [chromium/hstspreload.org#77]
```json
curl https://hstspreload.org/api/v2/preloadable\?domain\=procens.us
{
  "errors": [
    {
      "code": "response.no_header",
      "summary": "No HSTS header",
      "message": "Response error: No HSTS header is present on the response."
    }
  ],
  "warnings": [
    {
      "code": "redirects.http.useless_header",
      "summary": "Unnecessary HSTS header over HTTP",
      "message": "The HTTP page at http://procens.us sends an HSTS header. This has no effect over HTTP, and should be removed."
    }
  ]
}
```
<pre>
curl -i https://procens.us
HTTP/1.1 302 Moved Temporarily
Content-Length: 0
Connection: keep-alive
Date: Mon, 30 Jan 2017 10:04:41 GMT
Location: https://procensus.com/
Server: AmazonS3
Age: 314
Via: 1.1 3a991689c419c32ac90676d3bde92c5d.cloudfront.net (CloudFront)
<strong>Strict-Transport-Security: max-age=63072000; includeSubDomains; preload</strong>
X-Cache: Hit from cloudfront
X-Amz-Cf-Id: hir-CByqvvk-raYsbIRvY1NS3E8tES4v0-QKYiu7712-UhR6PYPWsg==
</pre>

**Comment by lgarron** [comment]
Hmm, the Go code is not receiving the header, possibly due to our custom transport options.

Do you know if CloudFront may be sending a conditional header based on details like the user agent?

**Comment by graingert** [comment]
I have no interest in not sending the header via HTTP as that seems like a pain with Lambda@Edge

**Comment by graingert** [comment]
I'm using lambda@edge with a response event trigger.  I have no access to who sent the request (user agent,  IP) or how they sent it (HTTP/HTTPS).

**Comment by lgarron** [comment]
> I have no interest in not sending the header via HTTP as that seems like a pain with Lambda@Edge

Aha. Well, then you'll just have to live with the warning (it won't block submission).

I've tried [sending a tweet](https://twitter.com/lgarron/status/826212294258421761) to @jeffbarr, who published [the post announcing the Lambda@Edge preview](https://aws.amazon.com/blogs/aws/coming-soon-lambda-at-the-edge/).

**Comment by graingert** [comment]
I can live with the warning. Is it possible for someone to manually bypass this, in this case?

**Comment by lgarron** [comment]
> Is it possible for someone to manually bypass this, in this case?

Yes, but people have been reporting a lot of new kinds of edge cases, so I wan to get to the bottom of things wherever possible.

**Comment by graingert** [comment]
@lgarron sure, but it can still be debugged while procens.us is added to the preload queue?

**Comment by graingert** [comment]
@lgarron uhh, looks like procens.us is on the preload list now, do you know what the fix was?

**Comment by lgarron** [comment]
No idea. :-/
