### ISSUE TITLE
Allow domains to end with . in search

### ISSUE THREAD

**Issue by lazzurs** [chromium/hstspreload.org#81]
Domains all end with a .

While we don't use this in most modern applications it is valid and the search of the list should allow domains to be searched for with a . at the end.

**Comment by lgarron** [comment]
Is there a use case this is important for?

**Comment by lgarron** [comment]
> Is there a use case this is important for?

Just to expand: this flexibility would come at a small maintenance cost, and no longer catch mistakes if people paste partial domains ending in a `.`

Given that no one has asked for this in several years, I'm wondering wondering if this is important enough to support.

**Comment by lazzurs** [comment]
Thanks for taking the time to respond.

The obvious answer is no, I can't imagine an important use case but it does fall into the 'liberal in what you accept' category.

I would suggest like email addresses domains are hard to validate and so running the query might be easier than trying to be clever here but I understand that a pull request would be better than a comment :)

**Comment by lgarron** [comment]
> I would suggest like email addresses domains are hard to validate and so running the query might be easier than trying to be clever here

Note that we need a canonical version of the domain to preload anyhow. If we decide to be liberal, we also need to figure out how to undo the liberalness, which I would rather not do if the current behaviour doesn't cause major interop problems.

Perhaps it would be appropriate to place this functionality into an "is this domain affected by the preload list" API, which could fix the capitalization, search ancestor domains, etc.

**Comment by lazzurs** [comment]
There is an error message which covers this and while it is not ideal behaviour from an automated point of view it does at least provide the correct response.
