### ISSUE TITLE
hstspreload preload detect domain with www always as subdomain

### ISSUE THREAD

**Issue by 4k2k** [chromium/hstspreload.org#92]
Testing my site for add to preload list I have these problems:

1) Testing with www: "Error: Subdomain" because I want add my site with www (I understand that a site with www is not a subdomain)

2) Testing without www: "Error: HTTP redirects to www first" and it was solved redirecting first from http://myste.com --> https://mysite.com and redirecting after from https://mysite.com --> https://www.mysite.com

What is issue? 
With this redirect I can add my site to preload list WITHOUT www but I cant add with WWW (I only want add my site with WWW) like I can see other sites preloaded as www.amazon.com where is preloaded with WWW and not with WWW

How can fix this issue for what preload dont detect my site www as subdomain?

**Comment by lgarron** [comment]
Automated submissions cannot preload `www` subdomains, because we want to encourage preloading the entire eTLD+1 for the best possible security.

You can [send an email to the contact address](https://hstspreload.org/#contact) if you would like to ask for an exception, but please note that the bar for exceptions is high.

**Comment by 4k2k** [comment]
Can I understand I dont need make any redirect if I ask for an exception to add my site only with www ?
Sites as amazon, facebook, twitter work with www because they ask for an exception?
How many months could be take to add site with www ?

**Comment by lgarron** [comment]
> Can I understand I dont need make any redirect if I ask for an exception to add my site only with www ?

You would still need to have some redirects, according to the requirements at https://hstspreload.org/#submission-requirements

> Sites as amazon, facebook, twitter work with www because they ask for an exception?

Yes, they have entries for their `www` subdomains because they were granted exceptions.

> How many months could be take to add site with www ?

The same as as adding any domain to the preload list: around 2-3 months.

**Comment by 4k2k** [comment]
> You would still need to have some redirects, according to the requirements at https://hstspreload.org/#submission-requirements<

Thank you very much, I have all domains and subdomains redirected directly to https://www
If I ask for an exception to preload only with www; Should I still redirect first from http:// to https:// (without www) and after from https:// to https:/www or as I dont want submit url without www then dont is necessary additionally redirect first to https (without www) ?

NOTE: Without www hstspreload only give me "Error: HTTP redirects to www first" but with www (as I wish) it give me only "Error: Subdomain"
