### ISSUE TITLE
JavaScript errors

### ISSUE THREAD

**Issue by bardiharborow** [chromium/hstspreload.org#94]
I'm now getting console errors when checking the status of a domain:

```
From URL parameter: google.com
view.js:92 Uncaught TypeError: Cannot set property 'textContent' of null
    at PreloadView._clearIssues (view.js:92)
    at PreloadView.clearDomainSpecificElements (view.js:53)
    at PreloadForm.checkDomain (form.js:25)
    at PreloadForm (form.js:18)
    at form.js:209
_clearIssues @ view.js:92
clearDomainSpecificElements @ view.js:53
checkDomain @ form.js:25
PreloadForm @ form.js:18
(anonymous) @ form.js:209
?domain=google.com:17 Uncaught ReferenceError: Form is not defined
    at ?domain=google.com:17
```

**Comment by lgarron** [comment]
Hmm, I have occasionally seen issues like this during development, probably
due to caching.
Does it work in a fresh browser profile?

**Comment by lgarron** [comment]
Yep, the `Form` object was introduced in 7e95ca16218c51e2dc766d5e18fa8815f5623f5b, so you have an outdated `form.js`.

**Comment by bardiharborow** [comment]
Yep. A hard reload fixed everything. I'm not sure if there's a way to prevent this happening in the future.
