### ISSUE TITLE
Increase waiting for GCD local store

### ISSUE THREAD

**Issue by vcsjones** [chromium/hstspreload.org#99]
I've gotten the local development setup on my computer (yay!) but I apparently have a slow-ish computer.

The `go run` command polls an HTTP endpoint to see that the local datastore is running:

https://github.com/chromium/hstspreload.org/blob/52a8473b03b2dffb7199bf6b7f6fd664788f4a34/database/gcd/gcd.go#L114-L117

This oddly just isn't enough time for my computer. I would suggest either increasing the number of probes or the time between probes. I set the probe interval to 4x the current value and now I am able to consistently get it up an running.

Thoughts?

**Comment by lgarron** [comment]
We also still get timeouts on Travis CI sometimes. I'd be happy to increase the number of probes.
